general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'a4675bb8trial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'

